[package]
name = "typewind"
version = "0.1.0"
edition = "2021"

[lib]
path = "typewind/lib.rs"

[dependencies]
glob = "0.3.1"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full", "visit"] }

[dev-dependencies]
tempfile = "3.14.0"
